baseurl      = "https://hydrabyte.netlify.app/"
title        = "Hydrabyte | Bawmc.net"
languageCode = "pt-br"
theme = "hello-friend-ng"

[pagination]
  pagerSize = 10


[languages.en.params.logo]
logoText = "Hydrabyte"
logoHomeLink = "/"

[[menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/posts"

[params]
# Subtitle for home
homeSubtitle = "“Atualize-se. Evolua. Expanda.”"
defaultTheme = "dark" # Pode ser "light", "dark" ou "auto"
disableThemeToggle = false # Habilita o botão de alternância de tema







[[params.social]]
  name = "discord"
  url = "https://discord.gg/KygeWUvD"

[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/gomes_ghx77?igsh=dHRzZTRlZnZ6dWkz"

[[params.social]]
  name = "github"
  url = "https://github.com/fluxmind-nhx/"

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"


